on:
  pull_request:
  push:
    branches: [main]
    tags: ["v*"]

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings"
  RUSTUP_MAX_RETRIES: 10

name: ci

jobs:
  hygiene:
    runs-on: ubuntu-latest

    steps:
      - name: Setup | Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Setup | Tools
        run: sudo apt-get install -y protobuf-compiler

      - name: Setup | Cache
        uses: Swatinem/rust-cache@v2

      - name: Build | Hygiene
        run: |
          cargo fmt  -- --check
          cargo clippy --all-features -- -D clippy::all

      - name: Build | Test
        run: |
          cargo test

  package:
    name: package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - armv7-nova-linux-musleabihf

    steps:
      - uses: actions/checkout@v3
      - uses: davidB/rust-cargo-make@v1
      - uses: dtolnay/rust-toolchain@stable

      - name: install cross
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        env:
          ## Allow cross install into PATH
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo: rust-embedded/cross

      - name: build target
        run: cargo make --profile ${{ matrix.target }} build

      - name: package release
        if: startsWith(github.ref, 'refs/tags')
        run: cargo make --profile ${{ matrix.target }} pkg

      - name: push release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fail_on_unmatched_files: true
          files: |
            gateway-onboarding-*.tar.gz
            gateway-onboarding-*.checksum
